version = 0.1
[default.deploy.parameters]
stack_name = "math-problems-generator"
resolve_s3 = true
s3_prefix = "math-problems-generator"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev"
